### PR TITLE
Modifiy ascii art to fit in smaller displays

### PR DESCRIPTION
**Pull request by alex5imon**
@radujipa @Ealdwulf these are the changes from @Roonio

### CODE REVIEW

**Comment by Ealdwulf** [comment]
Looks good!

**Comment by Ealdwulf** [comment]
Looks good!

**Comment by Ealdwulf** [comment]
Github having a bit of a glitch there.

**Comment by radujipa** [comment]
@Roonio Couple of things here: 

 - new line character is a `\r` instead of a `\n` if you look at it in `less`
 - lines width are `51` and `48` is the maximum on the lowest resolution
 - maximum number of lines per ascii art file is `25` on the lowest resolution

**Comment by Ealdwulf** [comment]
Merging this for testing.

**Pull request merged**
