### PR TITLE
Added a CapsLock notification in the SpellBook

### PR DESCRIPTION
**Pull request by radujipa**
screen shot 2016-01-27 at 17 00 42
`Resolution 1024x768`

Related to https://github.com/KanoComputing/peldins/issues/2192

### CODE REVIEW

**Comment by radujipa** [comment]
@neue happy with the design implementation?
@alex5imon could you please review?

**Comment by radujipa** [comment]
OK, had a look at fixing the 'delayed' notification response to key presses, i.e. Press to Set Caps > nothing > Press any key > Get notification.

I can't fix this due to a Kano Keyboard hardware/driver issue.

Here's why:

1) I cannot query the state (Gdk.Keymap.get_caps_lock_state() makes the app explode)
2) I can get the state from an `event.state` which I get after a `key-press/release-event`
3) To turn on Caps:
    `on_key_press:` flag gets set by keyboard, gtk doesn't see it
    `on_key_release:` flag is set by keyboard, gtk sees it
4) To turn off Caps:
    `on_key_press:` flag does not get set by keyboard, gtk doesn't see it
    `on_key_release:` flag gets set by keyboard, gtk doesn't see it (requires another event)

You can check the events by looking at the Caps Lock LEDs on the keyboard.
Now, unless I can fake press a key and get another set of press/release events, I cannot do this.

**Comment by Ealdwulf** [comment]
It looks like gtkEntry implements this by catching the `state-changed` event on the keymap: https://github.com/GNOME/gtk/blob/6e2c74aaad1c81fdab45d4e6d9febc5e193253bf/gtk/gtkentry.c#L4907
Maybe that would get it right when capslock is pressed. But only try if you have time.

**Comment by radujipa** [comment]
@Ealdwulf Had a quick look at this the `state-changed` event, which apparently is now deprecated. [state-flags-changed](http://lazka.github.io/pgi-docs/#Gtk-3.0/classes/Widget.html#Gtk.Widget.signals.state_flags_changed) is the newer event from Gtk.Widget, and it seems it only exports these [StateFlags](http://lazka.github.io/pgi-docs/#Gtk-3.0/flags.html#Gtk.StateFlags). If Gtk.Entry `state-changed` event behaves differently for some reason, I don't see a clear way how I'd use that given that the `key-pressed/released-event` are attached to the window. I'll make a note of it and will look at it later.

**Comment by Ealdwulf** [comment]
@radujipa state-changed is deprecated in GtkWidget, but I don't think it is in keymap: https://developer.gnome.org/gdk3/stable/gdk3-Keyboard-Handling.html#GdkKeymap-state-changed
But this should be fine for now.

**Pull request merged**
