### PR TITLE
Improvements (part 1)

### PR DESCRIPTION
**Pull request by radujipa**
This PR includes the following UI enhancements:

 - Highlighting effect for Spells when you receive New ones
   https://github.com/KanoComputing/peldins/issues/2195

 - Hover over effect for Spells to get more info about them 
   https://github.com/KanoComputing/peldins/issues/2196

 - Coming Soon scrolling animation inside the app
   https://github.com/KanoComputing/peldins/issues/2225

 - Copy and colouring changes/fixes throughout the game

### CODE REVIEW

**Comment by radujipa** [comment]
@alex5imon could you review please?

**Comment by alex5imon** [comment]
you need to update this https://github.com/KanoComputing/terminal-quest/blob/master/debian/copyright with the media files @radujipa

**Comment by radujipa** [comment]
@alex5imon, @neue has fixed the licenses

**Comment by radujipa** [comment]
@alex5imon I have also added the `Coming Soon` animation to this PR

**Comment by radujipa** [comment]
@alex5imon this is ready for merging and testing

**Comment by TeamKano** [comment]
Go for it!

@FMog will test the s*** out of it on Monday :)

**Pull request merged**
